export const serviceLogos: Record<string, string> = {
  Netflix: "/logos/netflix.svg",
  "Netflix Compte Perso": "/logos/netflix.svg",
  "IPTV Premium": "/logos/iptv.svg",
  myCANAL: "/logos/mycanal.svg",
  "Surfshark VPN": "/logos/surfshark.svg",
  "iCloud+": "/logos/icloud.svg",
  "Snapchat+": "/logos/snapchat.svg",
  "Apple Music": "/logos/apple-music.svg",
  "Apple TV+": "/logos/apple-tv.png",
  "Spotify Premium": "/logos/spotify.svg",
  "Deezer Premium": "/logos/deezer.svg",
  Hulu: "/logos/hulu.svg",
  "HBO Max": "/logos/max.svg",
  Crunchyroll: "/logos/crunchyroll.svg",
  "Prime Video": "/logos/prime-video.svg",
  "Prime Video Compte Perso": "/logos/prime-video.svg",
  "Disney+": "/logos/disney-plus.svg",
  "Pack Netflix + Prime Video": "/logos/netflix.svg",
  "Pack Netflix + Disney+": "/logos/netflix.svg",
  "Pack Prime Video + Disney+": "/logos/prime-video.svg",
  "ChatGPT Go": "/logos/chatgpt.png",
  "ChatGPT+ Co-abonnement": "/logos/chatgpt.png",
  "ChatGPT+ Individuel": "/logos/chatgpt.png",
  "CapCut Pro": "/logos/capcut.png",
  "Canva Pro": "/logos/canva.png",
  "FaceApp Pro": "/logos/faceapp.png",
  "Scribd Premium": "/logos/scribd.svg",
  "iCloud+ 50 Go": "/logos/icloud.svg",
  "iCloud+ 200 Go": "/logos/icloud.svg",
  "PUBG Mobile": "/logos/pubg-mobile.png",
  "Fortnite V-Bucks": "/logos/fortnite.png",
  "Valorant Points (EU)": "/logos/valorant.png",
  "PSN USA": "/logos/psn-usa.svg",
  "PSN France": "/logos/psn-france.svg",
  "iTunes France": "/logos/itunes.png",
  "iTunes USA": "/logos/itunes.png",
  "YouTube Premium": "/logos/youtube.svg",
};

export const spotlightServices = ["Netflix", "IPTV Premium"];
